In [2]:
import pandas as pd
import numpy as np
from datetime import datetime 
import seaborn as sn
import matplotlib.pyplot as plt

In [190]:
df = pd.read_csv(r"C:\Users\Luchiana\OneDrive - ONE NEW EXPERIENCE\Desktop\Audible_dataset.csv")
df.head(5)

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04/08/2008,English,5 out of 5 stars34 ratings,468
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01/05/2018,English,4.5 out of 5 stars41 ratings,820
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06/11/2020,English,4.5 out of 5 stars38 ratings,410
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05/10/2021,English,4.5 out of 5 stars12 ratings,615
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820

In [134]:
df.duplicated().sum()

0

In [162]:
df.isna().sum()

name           0
author         0
narrator       0
time           0
releasedate    0
language       0
stars          0
price          0
dtype: int64

In [191]:
df['releasedate']=pd.to_datetime(df['releasedate'])
df.head(10)

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,2008-04-08,English,5 out of 5 stars34 ratings,468
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,2018-01-05,English,4.5 out of 5 stars41 ratings,820
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,2020-06-11,English,4.5 out of 5 stars38 ratings,410
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,2021-05-10,English,4.5 out of 5 stars12 ratings,615
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,2010-01-13,English,4.5 out of 5 stars181 ratings,820
5,The Hunger Games: Special Edition,Writtenby:SuzanneCollins,Narratedby:TatianaMaslany,10 hrs and 35 mins,2018-10-30,English,5 out of 5 stars72 ratings,656
6,Quest for the Diamond Sword,Writtenby:WinterMorgan,Narratedby:LukeDaniels,2 hrs and 23 mins,2014-11-25,English,5 out of 5 stars11 ratings,233
7,The Dark Prophecy,Writtenby:RickRiordan,Narratedby:RobbieDaymond,12 hrs and 32 mins,2017-02-05,English,5 out of 5 stars50 ratings,820
8,Merlin Mission Collection,Writtenby:MaryPopeOsborne,Narratedby:MaryPopeOsborne,10 hrs and 56 mins,2017-02-05,English,5 out of 5 stars5 ratings,"1,256.00"
9,The Tyrant’s Tomb,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 22 mins,2019-09-24,English,5 out of 5 stars58 ratings,820

In [192]:
def replace_value(value):
    if 'Writtenby:' in value:
        return value.replace('Writtenby:','')
    elif 'Narratedby:' in value:
        return value.replace('Narratedby:', '')
    else:
        return value
    
df['author']= df['author'].apply(replace_value)

In [193]:
df['narrator']=df['narrator'].apply(replace_value)
df.head(5)

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,2008-04-08,English,5 out of 5 stars34 ratings,468
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,2018-01-05,English,4.5 out of 5 stars41 ratings,820
2,The Deep End,JeffKinney,DanRussell,2 hrs and 3 mins,2020-06-11,English,4.5 out of 5 stars38 ratings,410
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 hrs and 16 mins,2021-05-10,English,4.5 out of 5 stars12 ratings,615
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,10 hrs,2010-01-13,English,4.5 out of 5 stars181 ratings,820

In [194]:
def insert_space_before_upper(s):
    result=''
    
    for i in s:
        if i.isupper():
            result = result + " " + i
        else:
            result = result + i
    return result


df['author'] = df['author'].apply(insert_space_before_upper)
df['narrator']=df['narrator'].apply(insert_space_before_upper)

In [55]:
df.head(5)

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2 hrs and 20 mins,2008-04-08,English,5 out of 5 stars34 ratings,468
1,The Burning Maze,Rick Riordan,Robbie Daymond,13 hrs and 8 mins,2018-01-05,English,4.5 out of 5 stars41 ratings,820
2,The Deep End,Jeff Kinney,Dan Russell,2 hrs and 3 mins,2020-06-11,English,4.5 out of 5 stars38 ratings,410
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,11 hrs and 16 mins,2021-05-10,English,4.5 out of 5 stars12 ratings,615
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,10 hrs,2010-01-13,English,4.5 out of 5 stars181 ratings,820

In [195]:
df['language']=df['language'].str.capitalize()

In [196]:
#df[df['language']!='English']

df['rating'] = df['stars'].str.extract(r'(\d+ ratings)')
#df['stars'] = df['stars'].str.extract(r'(\d out of \d stars)')
df['stars'] =df['stars'].str.extract(r'(\d+)')

In [179]:
 #name = A Bear Called Paddington

In [197]:
df[df.name =='A Bear Called Paddington']

,name,author,narrator,time,releasedate,language,stars,price,rating
50,A Bear Called Paddington,Michael Bond,Stephen Fry,2 hrs and 39 mins,2008-06-24,English,NaN,266,NaN

In [198]:
df['stars'] = df['stars'].fillna(0)

In [199]:
df['stars'] = df['stars'].astype('int')

In [200]:
df.head()

,name,author,narrator,time,releasedate,language,stars,price,rating
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2 hrs and 20 mins,2008-04-08,English,5,468,34 ratings
1,The Burning Maze,Rick Riordan,Robbie Daymond,13 hrs and 8 mins,2018-01-05,English,4,820,41 ratings
2,The Deep End,Jeff Kinney,Dan Russell,2 hrs and 3 mins,2020-06-11,English,4,410,38 ratings
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,11 hrs and 16 mins,2021-05-10,English,4,615,12 ratings
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,10 hrs,2010-01-13,English,4,820,181 ratings